# Generated by Django 5.0 on 2024-02-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default=1, max_length=300, verbose_name='Подзаголовок записи'),
            preserve_default=False,
        ),
    ]
